### PR TITLE
Refactoring following the MVP pattern

### PR DESCRIPTION
**Pull request by zhouzi**

### CODE REVIEW

**Comment by clemp6r** [comment]
My first advice:

In MVP the view should instantiate the presenter, and it should call presenter methods directly. This also means that the "PubSub" event bus should not be used.

As a good practice, do not run logic in the presenter constructor, just initialize properties. You can add a presenter method "onViewReady()" or something if you need to run logic at startup.

Also MVP was designed to improve testability, so it would be nice to have Presenter tests (with a mocked View).

**Comment by zhouzi** [comment]
Thanks, I'll work on that!

How should I deal with the cases where I need to update the view from the Presenter (because it's the one causing changes)? Should I pass a reference to the view to the Presenter?

``` javascript
class View {
  constructor () {
    this.presenter = new Presenter(this)
  }
}

class Presenter {
  constructor (view) {
    this.view = view
  }
}
```

**Comment by clemp6r** [comment]
Exactly. In typed languages we define an interface for the view, so the presenter is highly decoupled from it (e.g: it can be tested using a fake view). In JS we have no interface so you have to make sure the presenter use the view without knowing how its implemented (a way to ensure this is to write the presenter entirely before writing the view class).

**Comment by zhouzi** [comment]
All done! Anything else I can improve @clemp6r? :)

**Pull request merged**
